name=MAX7219
version=1.0.0
author=Saurav Sajeev
maintainer=Saurav Sajeev
sentence=Driver for the MAX7219 LED matrix controller.
paragraph=The MAX7219 is a popular LED matrix controller that can drive up to 64 LEDs in a 8x8 grid. This library provides a simple interface to control the display and show patterns, text, and other graphics.
category=Display
url=https://github.com/styropyr0/MAX7219
architectures=*
license=MIT
